package com.example.ui

object Lang {
    private val translations = mapOf(
        "dashboard" to Pair("ڈیش بورڈ", "Dashboard"),
        "inventory" to Pair("اسٹاک رجسٹر", "Stock Inventory"),
        "pos" to Pair("بل بنائیں (POS)", "New Bill (POS)"),
        "ledger" to Pair("ادھار کھاتہ", "Udhaar Ledger"),
        "expenses" to Pair("اخراجات", "Expenses"),
        "admin" to Pair("مالک (ایڈمن)", "Owner (Admin)"),
        "cashier" to Pair("کیشیئر", "Cashier"),
        "role_toggle" to Pair("رول تبدیل کریں", "Toggle Role"),
        "today_sales" to Pair("آج کی کل فروخت", "Today's Sales"),
        "monthly_sales" to Pair("اس مہینے کی فروخت", "This Month's Sales"),
        "today_profit" to Pair("آج کا منافع", "Today's Net Profit"),
        "total_credit" to Pair("مارکیٹ میں کل ادھار", "Total Pending Udhaar"),
        "stock_alerts_title" to Pair("کم اسٹاک الرٹ", "Low Stock Alerts"),
        "no_stock_alerts" to Pair("سب اشیاء کا اسٹاک پورا ہے", "All items have sufficient stock"),
        "total_customers" to Pair("کل رجسٹرڈ گاہک", "Total Customers"),
        "total_expenses" to Pair("کل اخراجات", "Total Expenses"),
        "p_and_l" to Pair("نفع / نقصان کی رپورٹ", "Profit & Loss Report"),
        "revenue" to Pair("کل آمدنی", "Total Revenues"),
        "cogs" to Pair("اشیاء کی لاگت (خرید قیمت)", "Cost of Goods Sold"),
        "net_profit" to Pair("خالص منافع / بچت", "Net Saving (Profit)"),
        "add_item" to Pair("نیا آئٹم شامل کریں", "Add New Item"),
        "edit_item" to Pair("آئٹم کی ترمیم کریں", "Edit Item"),
        "item_name" to Pair("آئٹم کا نام", "Item Name"),
        "category" to Pair("کیٹیگری / زمرہ", "Category"),
        "purchase_price" to Pair("خریداری کی قیمت (خرید)", "Purchase Price"),
        "selling_price" to Pair("فروخت کی قیمت (فروخت)", "Selling Price"),
        "stock_qty" to Pair("دستیاب اسٹاک (تعداد)", "Stock Quantity"),
        "low_stock_limit" to Pair("الرٹ کی حد (کم از کم)", "Min Low-Stock Alert Level"),
        "barcode" to Pair("بارکوڈ نمبر", "Barcode Number"),
        "scan_camera" to Pair("کیمرہ سے اسکین کریں", "Scan via Camera"),
        "scan_sim" to Pair("بارکوڈ درج کریں (اسکین کے بجائے)", "Enter Barcode (Simulate Scan)"),
        "save" to Pair("محفوظ کریں", "Save & Register"),
        "delete" to Pair("حذف کریں", "Delete"),
        "cancel" to Pair("منسوخ کریں", "Cancel"),
        "search_hint" to Pair("نام یا بارکوڈ لکھیں...", "Search by Name or Barcode..."),
        "add_customer" to Pair("نیا گاہک شامل کریں", "Add Customer"),
        "edit_customer" to Pair("گاہک کی معلومات", "Customer Info"),
        "customer_name" to Pair("گاہک کا نام", "Customer Name"),
        "phone" to Pair("فون نمبر", "Phone Number"),
        "address" to Pair("پتہ / دکان", "Address"),
        "walk_in_customer" to Pair("ہاتھ کا گاہک (نقد)", "Walk-in Cash Customer"),
        "outstanding_udhaar" to Pair("واجب الادا ادھار", "Outstanding Udhaar Debit"),
        "payments_history" to Pair("ادائیگیوں کی تاریخ", "Account History"),
        "record_payment" to Pair("قسط / ادائیگی موصول کریں", "Record Payment Received"),
        "payment_amount" to Pair("موصولہ رقم (روپے)", "Received Amount (PKR)"),
        "notes" to Pair("تفصیل (نوٹ)", "Detail / Note"),
        "enter_payment" to Pair("ادائیگی درج کریں", "Save Receipt"),
        "add_to_cart" to Pair("کارٹ میں شامل کریں", "Add to Cart"),
        "cart" to Pair("فروخت کا کارٹ", "Sales Cart"),
        "cart_empty" to Pair("کارٹ خالی ہے الیکٹرانک بل بنانے کے لئے اشیاء منتخب کریں", "Cart is empty. Select products or scan barcode to sell."),
        "total_bill" to Pair("ٹوٹل بل", "Subtotal Bill"),
        "discount" to Pair("رعایت (ڈسکاؤنٹ)", "Discount (PKR)"),
        "payable_amount" to Pair("قابلِ ادائیگی رقم", "Final Payable"),
        "payment_type" to Pair("فروخت کی قسم", "Payment Mode"),
        "cash_sale" to Pair("نقد فروخت (Cash)", "Cash Sale"),
        "credit_sale" to Pair("ادھار کھاتہ (Udhaar)", "Credit (Udhaar) Sale"),
        "select_credit_customer" to Pair("ادھار کے گاہک کا انتخاب کریں", "Select Ledger Customer"),
        "complete_sale" to Pair("بل مکمل کریں", "Complete Sale & Print"),
        "expense_tracking" to Pair("اخراجات کا حساب", "Expense Ledger"),
        "add_expense" to Pair("نیا خرچہ درج کریں", "Record Expense"),
        "expense_category" to Pair("خرچے کی قسم", "Expense Category"),
        "amount" to Pair("رقم (روپے)", "Amount (PKR)"),
        "rent" to Pair("دکان کا کرایہ", "Rent"),
        "electricity" to Pair("بجلی / بل", "Electricity & Utilities"),
        "purchase_stock" to Pair("نیا گاہک مال خریداری", "Stock Supply Purchase"),
        "salaries" to Pair("ملازمین کی تنخواہ", "Salaries"),
        "others" to Pair("دیگر متفرق اخراجات", "Others / Miscellaneous"),
        "backup_restore" to Pair("بیک اپ اور ری اسٹور", "Backup & Restore"),
        "backup_desc" to Pair("تمام اسٹاک، کھاتہ، اور رپورٹس کا ٹیکسٹ بیک اپ لیں۔ آپ اسے مستقبل میں محفوظ کر سکتے ہیں۔", "Generate a manual text JSON backup of all store ledger data. Copy it to restore anytime."),
        "create_backup" to Pair("بیک اپ ڈیٹا بنائیں", "Copy Backup Data"),
        "restore_data" to Pair("پرانا بیک اپ بحال کریں", "Paste & Restore Backup"),
        "whatsapp_receipt" to Pair("واٹس ایپ پر رسید بھیجیں", "Send Receipt via WhatsApp"),
        "whatsapp_reminder" to Pair("ادھار یاد دہانی بھیجیں", "Send Udhaar Reminder"),
        "low_stock" to Pair("کم اسٹاک!", "Low Stock!"),
        "stock" to Pair("اسٹاک", "Stock"),
        "pk_currency" to Pair("روپے", "Rs."),
        "out_of_stock" to Pair("اسٹاک ختم ہو چکا ہے!", "Out of Stock!"),
        "success_sale" to Pair("بل کامیابی سے رجسٹر ہو گیا!", "Bill checkout completed successfully!"),
        "success_payment" to Pair("ادائیگی کامیابی سے رجسٹر ہو گئی!", "Payment recorded successfully!"),
        "success_product" to Pair("آئٹم کامیابی سے شامل ہو گیا!", "Product saved successfully!"),
        "success_customer" to Pair("گاہک کامیابی سے شامل ہو گیا!", "Customer registered successfully!"),
        "success_expense" to Pair("خرچہ کامیابی سے درج ہو گیا!", "Expense tracked successfully!"),
        "confirm_delete" to Pair("کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟", "Are you sure you want to delete this?"),
        "cashier_msg" to Pair("سیلز مین موڈ چالو ہے (تبدیلیاں محدود ہیں)", "Cashier Mode enabled (Modifications restricted)"),
        "receipt_header" to Pair("--- مدینہ کریانہ اسٹور ---", "--- Kiryana Receipt ---"),
        "invalid_barcode" to Pair("یہ بارکوڈ کسی آئٹم سے مطابقت نہیں رکھتا!", "Barcode not matched with any product!")
    )

    fun get(key: String, isUrdu: Boolean): String {
        val entry = translations[key] ?: return key
        return if (isUrdu) entry.first else entry.second
    }

    // Quick access
    fun getList(isUrdu: Boolean) = translations.keys.toList()
}
